negotiate-auth:
    path:       /auth
    defaults:   { _controller: 'SimpleSAML\Module\negotiateext\Controller\NegotiateController::auth' }

negotiate-error:
    path:       /error
    defaults:   { _controller: 'SimpleSAML\Module\negotiateext\Controller\NegotiateController::error' }

negotiate-enable:
    path:       /enable
    defaults:   { _controller: 'SimpleSAML\Module\negotiateext\Controller\NegotiateController::enable' }

negotiate-disable:
    path:       /disable
    defaults:   { _controller: 'SimpleSAML\Module\negotiateext\Controller\NegotiateController::disable' }

negotiate-retry:
    path:       /retry
    defaults:   { _controller: 'SimpleSAML\Module\negotiateext\Controller\NegotiateController::retry' }

negotiate-fallback:
    path:       /fallback
    defaults:   { _controller: 'SimpleSAML\Module\negotiateext\Controller\NegotiateController::fallback' }
